/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Jni */

#ifndef _Included_Jni
#define _Included_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Jni
 * Method:    print
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Jni_print
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
