LOCAL_PATH:=$(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE:=libhello
LOCAL_MODULE_PATH:=$(LOCAL_PATH)
LOCAL_SRC_FILES:=hello.c
LOCAL_SHARED_LIBRARIES:=liblog libhardware
include $(BUILD_SHARED_LIBRARY)

