/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Jni */

#ifndef _Included_Jni
#define _Included_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Jni
 * Method:    java_open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Jni_java_1open
  (JNIEnv *, jobject);

/*
 * Class:     Jni
 * Method:    java_ioctl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Jni_java_1ioctl
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Jni
 * Method:    java_close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Jni_java_1close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
